### ISSUE TITLE
aws cli doesn't work with blimp s3server endpoint

### ISSUE THREAD

**Issue by boddumanohar** [0chain/minio#78]
```
aws --endpoint-url https://blimpxname.zus.network/s3server --profile minio s3 ls
```

currently if I use aws cli with blimp endpoint, it doesn't work. 

But it works fine with the localhost endpoint. 

https://min.io/docs/minio/linux/integrations/aws-cli-with-minio.html

I am following these instructions

**Comment by sunilmhta** [comment]
So the aws client not working was a bug in our reverse proxy code. The s3 clients assume that we give them a pure url without any resource ie. some url of the form https://myurl/ it should not be of the form: `https://myurl/resource` When I changed the reverse proxy, so that minioserver start accepting all urls ending at / the aws cli started working.  Although this broke the logsearch and minioclient end points, will see if there is a way to coexist all 3 together.

<img width="815" alt="image" src="https://github.com/0chain/zs3server/assets/15699710/8aa725e8-dbd6-4920-82d3-13adb0bc8417">

**Comment by boddumanohar** [comment]
fixed by: https://github.com/0chain/zcnwebappscripts/pull/83
